In [ ]:
Pandas
In this module we will be learning about pandas, the python library for representing dataframes, tabular, 2-d structures that represent datasets.

We will talk about

Series: 1-dimensional representations of data
Dataframes: Basic concepts and manipulation of pandas 2-d data structures
Advanced dataframes: more advanced data frame manipulation
As we go through the curriculum, be sure to read the official pandas documentation as well.

There's not just one way to do it

As we go through the pandas lessons, you will undoubtedly find different ways to accomplish the same tasks that we are doing as you search the internet. For the sake of simplicty we will just present one way to do things, but keep in mind you will see other variations, and the pandas library has more depth to it than what we present here.

Further Reading
pandas tutorial recomendations from the official pandas docs
pandas compared to SQL
pandas cheat sheet
10 minutes to pandas (this one is extremely dense, but provides an overview of all of the functionality of pandas)

In [ ]:
The Pandas Series
Pandas provides a Series object that is very similar to a numpy array, but with some additional functionality. In this lesson, we will learn about pandas Series and how to work with them.

Overview
A pandas Series object is a one-dimensional, labeled array made up of an autogenerated index that starts at 0 and data of a single data type.

A couple of important things to note about a Series:

If I try to make a pandas Series using multiple data types like int and string values, the data will be converted to the same object data type; the int values will lose their int functionality.

A pandas Series can be created in several ways; we will look at a few of these ways below. However, it will most often be created by selecting a single column from a pandas Dataframe in which case the Series retains the same index as the Dataframe. We will dive into this in the next two lessons: DataFrames and Advanced DataFrames.

In [ ]:


import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
Convention is to import the pandas module with the alias pd.

Create a Series
We can use the pandas Series constructor function to create a Series:

from a Python list or a NumPy array.

numbers_series = pd.Series([100, 43, 26, 17, 17])
type(numbers_series)

pandas.core.series.Series

numbers_series

0    100
1     43
2     26
3     17
4     17
dtype: int64
Notice what happens when we create a Series containing different data types:


pd.Series([3, 2, 4.5])

0    3.0
1    2.0
2    4.5
dtype: float64

letters_series = pd.Series(['a', 'e', 'h', 'd', 'b', 'z'])
letters_series

0    a
1    e
2    h
3    d
4    b
5    z
dtype: object
from a Python dictionary.

labeled_series = pd.Series({'a' : 0, 'b' : 1.5, 'c' : 2, 'd': 3.5, 'e': 4, 'f': 5.5})
labeled_series

a    0.0
b    1.5
c    2.0
d    3.5
e    4.0
f    5.5
dtype: float64
Vectorized Operations
Like numpy arrays, pandas series are vectorized by default, for example, we can easily use the basic arithmatic operators to manipulate every element in the series.


numbers_series + 1

0    101
1     44
2     27
3     18
4     18
dtype: int64

numbers_series / 2

0    50.0
1    21.5
2    13.0
3     8.5
4     8.5
dtype: float64
Comparison operators also work:


numbers_series == 17

0    False
1    False
2    False
3     True
4     True
dtype: bool

numbers_series > 40

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
Series Attributes
Attributes return useful information about a Series' properties; they don't perform operations or calculations 
with the Series. Attributes are easily accessible using dot notation like we will see in the examples below. 
Jupyter Notebook allows you to quickly access a list of available attributes by pressing the tab key after 
the series name followed by a period or dot; this is called dot notation or attribute access.

There are several components that make up a pandas Series, and I can easliy access each component by using attributes.

.index
The index allows us to reference items in the series. In our numbers_series, the index consists of the numbers 0-3.

# Access the index of the Series using dot notation.

numbers_series.index

RangeIndex(start=0, stop=5, step=1)
.values
The values are my data.

# The values are stored in a NumPy array. Hello vectorized operations!

numbers_series.values

array([100,  43,  26,  17,  17])
.dtype
The dtype is the data type of the elements in the Series. In our numbers_series, the data type is int64; it was inferred from the data we used.

In [ ]:
Pandas has several main data types we will work with:

int: integer, whole number values
float: decimal numbers
bool: true or false values
object: strings
category: a fixed and limited set of string values

numbers_series.dtype

dtype('int64')
.name
The name is an optional human-friendly name for the Series.
Our Series doesn't have a name, but we can give it one:


numbers_series.name = 'Numbers'
numbers_series

0    100
1     43
2     26
3     17
4     17
Name: Numbers, dtype: int64
.size
The .size attribute returns an int representing the number of rows in the Series. NULL values are included.

numbers_series.size

5
.shape
The .shape attribute returns a tuple representing the rows and columns when used on a two-dimensional structure like a DataFrame, but it can also be used on a Series to return its number of rows. NULL values are included.

numbers_series.shape

(5,)
Series Methods
Methods used on pandas Series objects often return new Series objects; most also offer parameters with default 
settings designed to keep the user from mutating the original Series objects. (inplace=False)

If I want to save any manipulations or transformations I make on my Series, I can either assign the Series to a 
variable or adjust my parameters. Series have a number of useful methods that we can use for various sorts of 
manipulations and transformations; let's look at a few.

.head, .tail, .sample
The .head(n) method returns the first n rows in the Series; n = 5 by default. This method returns a new Series 
with the same indexing as the original Series.

The .tail(n) method returns the last n rows in the Series; n = 5 by default. Increase or decrease your value 
for n to return more or less than 5 rows.

The .sample(n) method returns a random sample of rows in the Series; n = 1 by default. Again, the index is retained.


numbers_series.head(2)

0    100
1     43
Name: Numbers, dtype: int64

numbers_series.tail(2)

3    17
4    17
Name: Numbers, dtype: int64

numbers_series.sample()

4    17
Name: Numbers, dtype: int64
.astype
We can convert the data types of the values in our Series with the .astype method.


num_strings = pd.Series([3, 4, 5, 6]).astype('str')
num_strings

0    3
1    4
2    5
3    6
dtype: object

floats = pd.Series([3, 4, 5, 6]).astype('float')
floats

0    3.0
1    4.0
2    5.0
3    6.0
dtype: float64

floats.astype('int')

0    3
1    4
2    5
3    6
dtype: int64
.value_counts
The .value_counts() method returns a new Series consisting of a labeled index representing the unique values from 
the original Series and values representing the frequency each unique value appears in the original Series. 
It's like performing a SQL GROUP BY with a COUNT.
This is an extremely useful method you will find yourself using often with Series containing object and 
category data types.

pd.Series(['a', 'b', 'a', 'c', 'b', 'a', 'd', 'a']).value_counts()

a    4
b    2
c    1
d    1
dtype: int64
.describe
The .describe method returns a Series of descriptive statistics on a pandas Series. The information it returns depends on the data type of the elements in the Series.


numbers_series.describe()

count      5.000000
mean      40.600000
std       34.861153
min       17.000000
25%       17.000000
50%       26.000000
75%       43.000000
max      100.000000
Name: Numbers, dtype: float64
More Descriptive Statistics Methods

In [ ]:
Pandas has a number of methods that can be used to view summary statistics about our data. The table below 
(taken from here) provides a summary of some of the most commonly used methods.

Function	Description
count	Number of non-NA observations
sum	Sum of values
mean	Mean of values
median	Arithmetic median of values
min	Minimum
max	Maximum
mode	Mode
abs	Absolute Value
std	Bessel-corrected sample standard deviation
quantile	Sample quantile (value at %)

{
    'count': numbers_series.count(),
    'sum': numbers_series.sum(),
    'mean': numbers_series.mean()
}

{'count': 5, 'sum': 203, 'mean': 40.6}
.nlargest, .nsmallest
These methods allow me to return the n largest or n smallest values from a pandas Series. I can set the 
keep parameter to first, last, or all to deal with duplicate largest or smallest values; this is quite handy.

The default argument for keep is shown below.


Series.nlargest(n=5, keep='first')
Series.nsmallest(n=5, keep='first')

numbers_series.nlargest(n=1)

0    100
Name: Numbers, dtype: int64

# If I want to return all of the lowest values, not just the first instance.

numbers_series.nsmallest(n=1, keep='all')

3    17
4    17

In [ ]:
Name: Numbers, dtype: int64
.sort_values, .sort_index
These are handy methods that allow you to either sort your Series values or index respectively in ascending or 
descending order.

I can use the parameters for these methods to customize my sorts to meet my needs.

letters_series.sort_values()

0    a
4    b
3    d
1    e
2    h
5    z
dtype: object

# The Series values retain their index from the original Series.

letters_series.sort_values(ascending=False)

5    z
2    h
1    e
3    d
4    b
0    a
dtype: object

# I can reset the index using this parameter if that meets my needs.

letters_series.sort_values(ignore_index=True)

0    a
1    b
2    d
3    e
4    h
5    z
dtype: object

# I can also sort by index values.

labeled_series.sort_index(ascending=False)

f    5.5
e    4.0
d    3.5
c    2.0
b    1.5
a    0.0
dtype: float64
Exercises Part I
Make a file named pandas_series.py or pandas_series.ipynb for the following exercises.

Use pandas to create a Series named fruits from the following list:


    ["kiwi", "mango", "strawberry", "pineapple", "gala apple", "honeycrisp apple", "tomato", "watermelon", "honeydew", "kiwi", "kiwi", "kiwi", "mango", "blueberry", "blackberry", "gooseberry", "papaya"]
Use Series attributes and methods to explore your fruits Series.

Determine the number of elements in fruits.

Output only the index from fruits.

Output only the values from fruits.

Confirm the data type of the values in fruits.

Output only the first five values from fruits. Output the last three values. Output two random values from fruits.

Run the .describe() on fruits to see what information it returns when called on a Series with string values.

Run the code necessary to produce only the unique string values from fruits.

Determine how many times each unique string value occurs in fruits.

Determine the string value that occurs most frequently in fruits.

Determine the string value that occurs least frequently in fruits.

Indexing and Subsetting
This is where the pandas index shines; we can select subsets of our data using index labels, index position, or boolean sequences (list, array, Series).

I can also pass a sequence of boolean values to the indexing operator, []; that sequence could be a list or array, but it can also be another pandas Series if the index of the boolean Series matches the original Series.


numbers_series

0    100
1     43
2     26
3     17
4     17
Name: Numbers, dtype: int64

# I can see that my condition is being met by the values at index 0 and index 1.

bools = numbers_series > 40
bools

0     True
1     True
2    False
3    False
4    False
Name: Numbers, dtype: bool

# I pass my boolean mask to the original Series to return the values that meet the condition.

numbers_series[bools]

0    100
1     43
Name: Numbers, dtype: int64

# I can simply pass my conditional expression into the indexing operator, too.

numbers_series[numbers_series > 40]

0    100
1     43
Name: Numbers, dtype: int64

# We can create compound logical statements to narrow/expand our subsetting options 
# Wrap parenthese around each comparison
# The pipe | character is the OR

x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Find the numbers that are even or greater than 7
x[(x % 2 == 0) | (x > 7)]

1     2
3     4
5     6
7     8
8     9
9    10
dtype: int64

# Alternative syntax without the parentheses
is_even = x % 2 == 0
greater_than_seven = x > 7

x[is_even & greater_than_seven]

7     8
9    10
dtype: int64

# Find the numbers that are even AND greater than 7
x[(x % 2 == 0) & (x > 7)]

7     8
9    10
dtype: int64

# Alternative syntax without the parentheses
is_even = x % 2 == 0
greater_than_seven = x > 7
x[is_even & greater_than_seven]

7     8
9    10
dtype: int64
More Series Attributes
.str
In addition to vectorized arithmetic operations, pandas also provides us with a way to vectorize string manipulation. Once we access the .str attribute, we can apply a string method to each string value in a Series. Performing string manipulation like this does not mutate my original Series; I have to assign my manipulation to a variable if I want to keep it.

For example, we can call the .lower method, which will convert each string value in the string_series to lowercase.


string_series = pd.Series(['Hello', 'CodeuP', 'StUDenTs'])
string_series

0       Hello
1      CodeuP
2    StUDenTs
dtype: object

string_series.str.lower()

0       hello
1      codeup
2    students
dtype: object

string_series.str.replace('e', '_')

0       H_llo
1      Cod_uP
2    StUD_nTs
dtype: object

# Since each method returns a Series, I can use method chaining like this.

string_series.str.lower().str.replace('e', '_')

0       h_llo
1      cod_up
2    stud_nts
dtype: object

# I can even use method chaining and indexing!

string_series[string_series.str.lower().str.startswith('h')]

0    Hello
dtype: object

# Notice my original string_series is not mutated. 

string_series

0       Hello
1      CodeuP
2    StUDenTs
dtype: object
More Series Methods
.any, .all
We can use the .any method to check if any value in the series is True, and .all, to check if every value in a Series is True. Both methods return a boolean value denoting whether the condition is met.

For example, we could check to see if there are any negative values in a Series like this:


(numbers_series < 0).any()

False

(numbers_series < 0).all()

False
We could check if all the numbers are positive like this:


(numbers_series > 0).any()

True

(numbers_series > 0).all()

True
.isin
The .isin method can be used to tell whether each element in a Series matches an element in a passed sequence of values. For example, if we have a Series of letters, we could use .isin to tell whether each letter is a vowel.


# Create a list of vowels.

vowels = list('aeiou')
vowels

['a', 'e', 'i', 'o', 'u']

# Create a list of letters.

letters = list('abcdefghijk')
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']

# Construct a pandas Series from my list of letters.

letters_series = pd.Series(letters)
letters_series

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
dtype: object

# Use .isin to check if each element in letters_series matches an element in my list of vowels.

letters_series.isin(vowels)

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9     False
10    False
dtype: bool

# Use my Series of boolean values to return the values that meet my condition.

letters_series[letters_series.isin(vowels)]

0    a
4    e
8    i
dtype: object
.apply
Sometimes there are more complicated operations that we want to perform, and we need to apply a function to each element in a Series. In this case, we can define a function that handles a single value and use the .apply method to apply the function to each element in a Series.


def even_or_odd(n):
    '''
    A function that takes a number and returns a string indicating whether the passed number is even or odd.

    >>> even_or_odd(3)
    'odd'
    >>> even_or_odd(2)
    'even'
    '''
    if n % 2 == 0:
        return 'even'
    else:
        return 'odd'

numbers_series.apply(even_or_odd)

0    even
1     odd
2    even
3     odd
4     odd
Name: Numbers, dtype: object
Here we define a function, even_or_odd, then reference that function when we call .apply. Notice that when we reference the even_or_odd function, we are not calling the function, rather, we are passing the even_or_odd function itself to the .apply method as an argument, which pandas will then call on every element of the Series.

It is also very common to see lambda functions used along with .apply. We could re-write the above example with a lambda function like so:


numbers_series.apply(lambda n: 'even' if n % 2 == 0 else 'odd')

0    even
1     odd
2    even
3     odd
4     odd
Name: Numbers, dtype: object
Exercises Part II
Explore more attributes and methods while you continue to work with the fruits Series.

Capitalize all the string values in fruits.

Count the letter "a" in all the string values (use string vectorization).

Output the number of vowels in each and every string value.

Write the code to get the longest string value from fruits.

Write the code to get the string values with 5 or more letters in the name.

Find the fruit(s) containing the letter "o" two or more times.

Write the code to get only the string values containing the substring "berry".

Write the code to get only the string values containing the substring "apple".

Which string value contains the most vowels?

Binning Data
I can bin continuous data to convert it to categorical data. We will look at two different ways to accomplish binning below.


s = pd.Series(list(range(15)))
s

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
dtype: int64
pd.cut(s, bins=n)
We can either specify the number of bins to create, and pandas will create bins of equal size, or we can specify the bin edges ourselves by passing a list of bin edges or cutoffs.


# Bin values into 3 equal-sized bins.

pd.cut(s, 3)

0     (-0.014, 4.667]
1     (-0.014, 4.667]
2     (-0.014, 4.667]
3     (-0.014, 4.667]
4     (-0.014, 4.667]
5      (4.667, 9.333]
6      (4.667, 9.333]
7      (4.667, 9.333]
8      (4.667, 9.333]
9      (4.667, 9.333]
10      (9.333, 14.0]
11      (9.333, 14.0]
12      (9.333, 14.0]
13      (9.333, 14.0]
14      (9.333, 14.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.014, 4.667] < (4.667, 9.333] < (9.333, 14.0]]

# Bin values into bins with the cutoffs I specify. The bins are no longer of equal size.

pd.cut(s, [-1, 3, 12, 16])

0      (-1, 3]
1      (-1, 3]
2      (-1, 3]
3      (-1, 3]
4      (3, 12]
5      (3, 12]
6      (3, 12]
7      (3, 12]
8      (3, 12]
9      (3, 12]
10     (3, 12]
11     (3, 12]
12     (3, 12]
13    (12, 16]
14    (12, 16]
dtype: category
Categories (3, interval[int64, right]): [(-1, 3] < (3, 12] < (12, 16]]

# How many values fall into each bin? I can chain on the value_counts method.

pd.cut(s, 3).value_counts()

(-0.014, 4.667]    5
(4.667, 9.333]     5
(9.333, 14.0]      5
dtype: int64
value_counts(bins=n)
The value_counts method can also be valuable here. It has a parameter named bins, which will allow us to quickly bin and group our data at the same time if that is our desired end goal.


s.value_counts(bins=3)

(-0.015, 4.667]    5
(4.667, 9.333]     5
(9.333, 14.0]      5
dtype: int64
Plotting Data
The .plot() method allows us to quickly visualize the data in a Series. It's built on top of Matplotlib!

By default, Matplotlib will choose the best type of plot for us.

We can also customize our plot using the paramters of the .plot method or by using Matplot lib if we like. We will look at examples of both ways below.

Check the docs here for more on the .plot() method.


# Matplotlib is choosing the plot for us here, and it might tell the story we want.

nums_series = pd.Series([1, 5, 5, 5, 10, 20, 100, 40])
nums_series.plot()

plt.show()
png

We can also use specific types of visualizations like this:


# So, here we specify the type of plot we would like Matplotlib to use.
nums_series.plot.hist()

plt.show()
png

The .value_counts method returns a Series, so we can call .plot method on the resulting Series; this is called method chaining.


# Construct the Series.
lets_series = pd.Series(['a', 'b', 'a', 'c', 'b', 'a', 'd', 'a'])

# Plot the value_counts of our Series. Rotate our x-tick values.
lets_series.value_counts().plot.bar(rot=0)

plt.show()
png

Any additional keyword arguments passed to pandas .plot method will be passed along to the corresponding Matplotlib functions. In addition, we can use Matplotlib the same way we have before to set titles, tweak axis labels, etc. Let's look at both ways.


# Use the parameters of the .plot method to customize my chart.

pd.Series(['a', 'b', 'a', 'c', 'b', 'a', 'd', 'a']).value_counts().plot.bar(title='Example Pandas Visualization', 
                                                                            rot=0, 
                                                                            color='firebrick', 
                                                                            ec='black',
                                                                            width=.9).set(xlabel='Letter',
                                                                                         ylabel='Frequency')

plt.show()
png


# Use Matplotlib to customize.

pd.Series(['a', 'b', 'a', 'c', 'b', 'a', 'd', 'a']).value_counts().plot.bar(color='firebrick', width=.9)
plt.title('Example Pandas Visualization')
plt.xticks(rotation=0)
plt.xlabel('Letter')
plt.ylabel('Frequency')

plt.show()
png

Further Reading
pandas intro tutorials on
pandas user guide
pandas documentation: Series
Exercises Part III
Use pandas to create a Series named letters from the following string. The easiest way to make this string into a Pandas series is to use list to convert each individual letter into a single string on a basic Python list.


    'hnvidduckkqxwymbimkccexbkmqygkxoyndmcxnwqarhyffsjpsrabtjzsypmzadfavyrnndndvswreauxovncxtwzpwejilzjrmmbbgbyxvjtewqthafnbkqplarokkyydtubbmnexoypulzwfhqvckdpqtpoppzqrmcvhhpwgjwupgzhiofohawytlsiyecuproguy'
Which letter occurs the most frequently in the letters Series?

Which letter occurs the Least frequently?

How many vowels are in the Series?

How many consonants are in the Series?

Create a Series that has all of the same letters but uppercased.

Create a bar plot of the frequencies of the 6 most commonly occuring letters.

Use pandas to create a Series named numbers from the following list:


    ['$796,459.41', '$278.60', '$482,571.67', '$4,503,915.98', '$2,121,418.3', '$1,260,813.3', '$87,231.01', '$1,509,175.45', '$4,138,548.00', '$2,848,913.80', '$594,715.39', '$4,789,988.17', '$4,513,644.5', '$3,191,059.97', '$1,758,712.24', '$4,338,283.54', '$4,738,303.38', '$2,791,759.67', '$769,681.94', '$452,650.23']
What is the data type of the numbers Series?

How many elements are in the number Series?

Perform the necessary manipulations by accessing Series attributes and methods to convert the numbers Series to a numeric data type.

Run the code to discover the maximum value from the Series.

Run the code to discover the minimum value from the Series.

What is the range of the values in the Series?

Bin the data into 4 equally sized intervals or bins and output how many values fall into each bin.

Plot the binned data in a meaningful way. Be sure to include a title and axis labels.

Use pandas to create a Series named exam_scores from the following list:


    [60, 86, 75, 62, 93, 71, 60, 83, 95, 78, 65, 72, 69, 81, 96, 80, 85, 92, 82, 78]
How many elements are in the exam_scores Series?

Run the code to discover the minimum, the maximum, the mean, and the median scores for the exam_scores Series.

Plot the Series in a meaningful way and make sure your chart has a title and axis labels.

Write the code necessary to implement a curve for your exam_grades Series and save this as curved_grades. Add the necessary points to the highest grade to make it 100, and add the same number of points to every other score in the Series as well.

Use a method to convert each of the numeric values in the curved_grades Series into a categorical value of letter grades. For example, 86 should be a 'B' and 95 should be an 'A'. Save this as a Series named letter_grades.

Plot your new categorical letter_grades Series in a meaninful way and include a title and axis labels.

More Practice
Revisit the exercises from https://gist.github.com/ryanorsinger/f7d7c1dd6a328730c04f3dc5c5c69f3a.

After you complete each set of Series exercises, use any extra time you have to pursue the challenge below. You can work on these in the same notebook or file as the Series exercises or create a new practice notebook you can work in a little every day to keep your python and pandas skills sharp by trying to solve problems in multiple ways. These are not a part of the Series exercises grade, so don't worry if it takes you days or weeks to meet the challenge.

Challenge yourself to be able to...

solve each using vanilla python.

solve each using list comprehensions.

solve each by using a pandas Series for the data structure instead of lists and using vectorized operations instead of loops and list comprehensions.

In [1]:
import pandas as pd
import numpy as np
import pydataset import data

In [2]:
my_list = [2,3,5]

In [3]:
type(my_list)

list

# create a series from an array

In [4]:
my_series = pd.Series(my_list)

In [5]:
my_series

0    2
1    3
2    5
dtype: int64

In [6]:
my_array = np.array(my_list)

In [7]:
my_array

array([2, 3, 5])

In [8]:
my_series = pd.Series(my_array)

In [9]:
my_series

0    2
1    3
2    5
dtype: int64